### ISSUE TITLE
Circle imported as multiple ellipses

### ISSUE THREAD

**Issue by MatthiasJ1** [snoyer/ocpsvg#21]
https://github.com/gumyr/build123d/issues/520

**Comment by snoyer** [comment]
Currently all SVG shapes are first converted to SVG paths by the underlying `svgelements` library before we convert them to OCC curves. In this case I'm assuming your circle is indeed imported as 4 trimmed ellipses each representing a quarter of the circle.

I believe it should be possible to do a minor refactor to allow converting SVG circles/ellipses directly as OCC circles/ellipses without chunking them into arcs first. I'll look into it.

Assuming, of course, that this is the behavior you expect without having actually stated that much in your issue
